package com.iaito.service;

import java.util.List;

import com.iaito.dto.ContainerMovementAtFixedReaderDTO;
import com.iaito.model.ContainerMovementAtFixedReader;
import com.iaito.model.VehicleDevice;

public interface ContainerMovementAtFixedReaderService {

	public String addContainerMovementAtFixedReader(ContainerMovementAtFixedReader containerMovementAtFixedReader);
	public ContainerMovementAtFixedReaderDTO updateContainerMovementAtFixedReader(ContainerMovementAtFixedReader containerMovementAtFixedReader);
	public ContainerMovementAtFixedReaderDTO getContainerMovementAtFixedReaderByID(long movementId);
	public List<ContainerMovementAtFixedReaderDTO> getContainerMovementAtFixedReaderByReaderID(long readerId);
	public List<ContainerMovementAtFixedReaderDTO> getContainerMovementAtFixedReaderByEPC(String epc);
	public List<ContainerMovementAtFixedReaderDTO> getContainerMovementAtFixedReaderByContainerID(long containerId);
	public List<ContainerMovementAtFixedReaderDTO> getAllContainerMovementAtFixedReader();
	public void deleteContainerMovementAtFixedReader(ContainerMovementAtFixedReader containerMovementAtFixedReader);
	public String addContainerMovementAtRover(VehicleDevice vehicleDevice);
	public List<ContainerMovementAtFixedReaderDTO> getContainerMovementByContainerNumber(String containerNo);
	public ContainerMovementAtFixedReaderDTO getLastLocationByContainerNumber(String containerNo);
}
